# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

class Ui_DialogDistancierLay(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(390, 250)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 200, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 40, 221, 22))
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 42, 91, 20))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBoxb = QtGui.QComboBox(Dialog)
        self.comboBoxb.setGeometry(QtCore.QRect(140, 80, 221, 22))
        self.comboBoxb.setFont(font)
        self.comboBoxb.setObjectName("comboBoxb")
        self.labelb = QtGui.QLabel(Dialog)
        self.labelb.setGeometry(QtCore.QRect(30, 82, 91, 20))
        self.labelb.setFont(font)
        self.labelb.setObjectName("labelb")
        self.comboBoxc = QtGui.QComboBox(Dialog)
        self.comboBoxc.setGeometry(QtCore.QRect(140, 120, 221, 22))
        self.comboBoxc.setFont(font)
        self.comboBoxc.setObjectName("comboBoxc")
        self.labelc = QtGui.QLabel(Dialog)
        self.labelc.setGeometry(QtCore.QRect(30, 122, 91, 20))
        self.labelc.setFont(font)
        self.labelc.setObjectName("labelc")
        self.comboBoxd = QtGui.QComboBox(Dialog)
        self.comboBoxd.setGeometry(QtCore.QRect(140, 160, 221, 22))
        self.comboBoxd.setFont(font)
        self.comboBoxd.setObjectName("comboBoxd")
        self.labeld = QtGui.QLabel(Dialog)
        self.labeld.setGeometry(QtCore.QRect(30, 162, 91, 20))
        self.labeld.setFont(font)
        self.labeld.setObjectName("labeld")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Personnel", None))
        self.labelb.setText(QtGui.QApplication.translate("Dialog", "Etablissement", None))
        self.labelc.setText(QtGui.QApplication.translate("Dialog", "Type Distancier", None))
        t = u"Données Réseau"
        self.labeld.setText(t.encode('latin-1'))

