# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

class Ui_DialogDistancierInfoShp2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 290)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(440, 240, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(160, 40, 201, 22))
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 42, 111, 20))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBoxb = QtGui.QComboBox(Dialog)
        self.comboBoxb.setGeometry(QtCore.QRect(160, 80, 201, 22))
        self.comboBoxb.setFont(font)
        self.comboBoxb.setObjectName("comboBoxb")
        self.labelb = QtGui.QLabel(Dialog)
        self.labelb.setGeometry(QtCore.QRect(30, 82, 111, 20))
        self.labelb.setFont(font)
        self.labelb.setObjectName("labelb")
        self.comboBoxc = QtGui.QComboBox(Dialog)
        self.comboBoxc.setGeometry(QtCore.QRect(160, 120, 201, 22))
        self.comboBoxc.setFont(font)
        self.comboBoxc.setObjectName("comboBoxc")
        self.labelc = QtGui.QLabel(Dialog)
        self.labelc.setGeometry(QtCore.QRect(30, 122, 111, 20))
        self.labelc.setFont(font)
        self.labelc.setObjectName("labelc")
        self.comboBoxd = QtGui.QComboBox(Dialog)
        self.comboBoxd.setGeometry(QtCore.QRect(160, 160, 201, 22))
        self.comboBoxd.setFont(font)
        self.comboBoxd.setObjectName("comboBoxd")
        self.labeld = QtGui.QLabel(Dialog)
        self.labeld.setGeometry(QtCore.QRect(30, 162, 111, 20))
        self.labeld.setFont(font)
        self.labeld.setObjectName("labeld")
        self.comboBoxe = QtGui.QComboBox(Dialog)
        self.comboBoxe.setGeometry(QtCore.QRect(160, 200, 201, 22))
        self.comboBoxe.setFont(font)
        self.comboBoxe.setObjectName("comboBoxe")
        self.labele = QtGui.QLabel(Dialog)
        self.labele.setGeometry(QtCore.QRect(30, 202, 111, 20))
        self.labele.setFont(font)
        self.labele.setObjectName("labele")

        self.comboBox2 = QtGui.QComboBox(Dialog)
        self.comboBox2.setGeometry(QtCore.QRect(530, 40, 201, 22))
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.label2 = QtGui.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(400, 42, 111, 20))
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.comboBox2b = QtGui.QComboBox(Dialog)
        self.comboBox2b.setGeometry(QtCore.QRect(530, 80, 201, 22))
        self.comboBox2b.setFont(font)
        self.comboBox2b.setObjectName("comboBox2b")
        self.label2b = QtGui.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(400, 82, 111, 20))
        self.label2b.setFont(font)
        self.label2b.setObjectName("label2b")
        self.comboBox2c = QtGui.QComboBox(Dialog)
        self.comboBox2c.setGeometry(QtCore.QRect(530, 120, 201, 22))
        self.comboBox2c.setFont(font)
        self.comboBox2c.setObjectName("comboBox2c")
        self.label2c = QtGui.QLabel(Dialog)
        self.label2c.setGeometry(QtCore.QRect(400, 122, 111, 20))
        self.label2c.setFont(font)
        self.label2c.setObjectName("label2c")
        self.comboBox2d = QtGui.QComboBox(Dialog)
        self.comboBox2d.setGeometry(QtCore.QRect(530, 160, 201, 22))
        self.comboBox2d.setFont(font)
        self.comboBox2d.setObjectName("comboBox2d")
        self.label2d = QtGui.QLabel(Dialog)
        self.label2d.setGeometry(QtCore.QRect(400, 162, 111, 20))
        self.label2d.setFont(font)
        self.label2d.setObjectName("label2d")
        self.comboBox2e = QtGui.QComboBox(Dialog)
        self.comboBox2e.setGeometry(QtCore.QRect(530, 200, 201, 22))
        self.comboBox2e.setFont(font)
        self.comboBox2e.setObjectName("comboBox2e")
        self.label2e = QtGui.QLabel(Dialog)
        self.label2e.setGeometry(QtCore.QRect(400, 202, 111, 20))
        self.label2e.setFont(font)
        self.label2e.setObjectName("label2e")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Personnel ID", None))
        t = u"Réseau Voiture Dep_ID"
        self.labelb.setText(t.encode('latin-1'))
        t2 = u"Réseau Voiture Temps"
        self.labelc.setText(t2.encode('latin-1'))
        t4 = u"Réseau TC Dep_ID"
        self.labeld.setText(t4.encode('latin-1'))
        t5 = u"Réseau TC Temps"
        self.labele.setText(t5.encode('latin-1'))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Etablissement ID", None))
        t3 = u"Réseau Voiture Arr_ID"
        self.label2b.setText(t3.encode('latin-1'))
        self.label2c.setText(QtGui.QApplication.translate("Dialog", "Noeuds Voiture ID", None))
        t6 = u"Réseau TC Arr_ID"
        self.label2d.setText(t6.encode('latin-1'))
        self.label2e.setText(QtGui.QApplication.translate("Dialog", "Noeuds TC ID", None))
