# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

class Ui_DialogDistancierInfoShp(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 210)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        Dialog.setFont(font)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(440, 160, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 40, 221, 22))
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 42, 91, 20))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBoxb = QtGui.QComboBox(Dialog)
        self.comboBoxb.setGeometry(QtCore.QRect(140, 80, 221, 22))
        self.comboBoxb.setFont(font)
        self.comboBoxb.setObjectName("comboBoxb")
        self.labelb = QtGui.QLabel(Dialog)
        self.labelb.setGeometry(QtCore.QRect(30, 82, 91, 20))
        self.labelb.setFont(font)
        self.labelb.setObjectName("labelb")
        self.comboBoxc = QtGui.QComboBox(Dialog)
        self.comboBoxc.setGeometry(QtCore.QRect(140, 120, 221, 22))
        self.comboBoxc.setFont(font)
        self.comboBoxc.setObjectName("comboBoxc")
        self.labelc = QtGui.QLabel(Dialog)
        self.labelc.setGeometry(QtCore.QRect(30, 122, 91, 20))
        self.labelc.setFont(font)
        self.labelc.setObjectName("labelc")

        self.comboBox2 = QtGui.QComboBox(Dialog)
        self.comboBox2.setGeometry(QtCore.QRect(510, 40, 221, 22))
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.label2 = QtGui.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(400, 42, 91, 20))
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.comboBox2b = QtGui.QComboBox(Dialog)
        self.comboBox2b.setGeometry(QtCore.QRect(510, 80, 221, 22))
        self.comboBox2b.setFont(font)
        self.comboBox2b.setObjectName("comboBox2b")
        self.label2b = QtGui.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(400, 82, 91, 20))
        self.label2b.setFont(font)
        self.label2b.setObjectName("label2b")
        self.comboBox2c = QtGui.QComboBox(Dialog)
        self.comboBox2c.setGeometry(QtCore.QRect(510, 120, 221, 22))
        self.comboBox2c.setFont(font)
        self.comboBox2c.setObjectName("comboBox2c")
        self.label2c = QtGui.QLabel(Dialog)
        self.label2c.setGeometry(QtCore.QRect(400, 122, 91, 20))
        self.label2c.setFont(font)
        self.label2c.setObjectName("label2c")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Personnel ID", None))
        t = u"Réseau Dep_ID"
        self.labelb.setText(t.encode('latin-1'))
        t2 = u"Réseau Temps"
        self.labelc.setText(t2.encode('latin-1'))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Etablissement ID", None))
        t3 = u"Réseau Arr_ID"
        self.label2b.setText(t3.encode('latin-1'))
        self.label2c.setText(QtGui.QApplication.translate("Dialog", "Noeuds ID", None))
