# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

class Ui_DialogDistancierInfoShp(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(790, 250)
        font = QtGui.QFont()
        Dialog.setFont(font)
        font.setFamily("Calibri")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 200, 291, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(150, 40, 221, 22))
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 42, 101, 20))
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBoxb = QtGui.QComboBox(Dialog)
        self.comboBoxb.setGeometry(QtCore.QRect(150, 80, 221, 22))
        self.comboBoxb.setFont(font)
        self.comboBoxb.setObjectName("comboBoxb")
        self.labelb = QtGui.QLabel(Dialog)
        self.labelb.setGeometry(QtCore.QRect(30, 82, 101, 20))
        self.labelb.setFont(font)
        self.labelb.setObjectName("labelb")
        self.comboBoxc = QtGui.QComboBox(Dialog)
        self.comboBoxc.setGeometry(QtCore.QRect(150, 120, 221, 22))
        self.comboBoxc.setFont(font)
        self.comboBoxc.setObjectName("comboBoxc")
        self.labelc = QtGui.QLabel(Dialog)
        self.labelc.setGeometry(QtCore.QRect(30, 122, 101, 20))
        self.labelc.setFont(font)
        self.labelc.setObjectName("labelc")
        self.comboBoxd = QtGui.QComboBox(Dialog)
        self.comboBoxd.setGeometry(QtCore.QRect(150, 160, 221, 22))
        self.comboBoxd.setFont(font)
        self.comboBoxd.setObjectName("comboBoxd")
        self.labeld = QtGui.QLabel(Dialog)
        self.labeld.setGeometry(QtCore.QRect(30, 162, 101, 20))
        self.labeld.setFont(font)
        self.labeld.setObjectName("labeld")

        self.comboBox2 = QtGui.QComboBox(Dialog)
        self.comboBox2.setGeometry(QtCore.QRect(530, 40, 221, 22))
        self.comboBox2.setFont(font)
        self.comboBox2.setObjectName("comboBox2")
        self.label2 = QtGui.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(410, 42, 101, 20))
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.comboBox2b = QtGui.QComboBox(Dialog)
        self.comboBox2b.setGeometry(QtCore.QRect(530, 80, 221, 22))
        self.comboBox2b.setFont(font)
        self.comboBox2b.setObjectName("comboBox2b")
        self.label2b = QtGui.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(410, 82, 101, 20))
        self.label2b.setFont(font)
        self.label2b.setObjectName("label2b")
        self.comboBox2c = QtGui.QComboBox(Dialog)
        self.comboBox2c.setGeometry(QtCore.QRect(530, 120, 221, 22))
        self.comboBox2c.setFont(font)
        self.comboBox2c.setObjectName("comboBox2c")
        self.label2c = QtGui.QLabel(Dialog)
        self.label2c.setGeometry(QtCore.QRect(410, 122, 101, 20))
        self.label2c.setFont(font)
        self.label2c.setObjectName("label2c")
        self.comboBox2d = QtGui.QComboBox(Dialog)
        self.comboBox2d.setGeometry(QtCore.QRect(530, 160, 221, 22))
        self.comboBox2d.setFont(font)
        self.comboBox2d.setObjectName("comboBox2d")
        self.label2d = QtGui.QLabel(Dialog)
        self.label2d.setGeometry(QtCore.QRect(410, 162, 101, 20))
        self.label2d.setFont(font)
        self.label2d.setObjectName("label2d")

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Personnel ID", None))
        t = u"Réseau Dep_ID"
        self.labelb.setText(t.encode('latin-1'))
        t2 = u"Réseau Temps"
        self.labelc.setText(t2.encode('latin-1'))
        t4 = u"Personnel Métier"
        self.labeld.setText(t4.encode('latin-1'))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Etablissement ID", None))
        t3 = u"Réseau Arr_ID"
        self.label2b.setText(t3.encode('latin-1'))
        self.label2c.setText(QtGui.QApplication.translate("Dialog", "Noeuds ID", None))
        t5 = u"Etablissement Métier"
        self.label2d.setText(t5.encode('latin-1'))
